import { Json as JsonComponent, JsonProps } from "./Json"
import { Meta, Story } from "@storybook/react"

const disableControl = {
  table: {
    disable: true,
  },
}

// noinspection JSUnusedGlobalSymbols
export default {
  argTypes: {
    align: disableControl,
    alignContent: disableControl,
    alignItems: disableControl,
    alignSelf: disableControl,
    borderBottom: disableControl,
    borderColor: disableControl,
    borderLeft: disableControl,
    borderRadius: disableControl,
    borderRight: disableControl,
    borderTop: disableControl,
    bottom: disableControl,
    boxSizing: disableControl,
    classes: disableControl,
    color: disableControl,
    columnGap: disableControl,
    display: disableControl,
    flex: disableControl,
    flexBasis: disableControl,
    flexDirection: disableControl,
    flexGrow: disableControl,
    flexShrink: disableControl,
    flexWrap: disableControl,
    fontFamily: disableControl,
    fontSize: disableControl,
    fontStyle: disableControl,
    gap: disableControl,
    gridArea: disableControl,
    gridAutoColumns: disableControl,
    gridAutoFlow: disableControl,
    gridAutoRows: disableControl,
    gridColumn: disableControl,
    gridRow: disableControl,
    gridTemplateAreas: disableControl,
    gridTemplateColumns: disableControl,
    gridTemplateRows: disableControl,
    gutterBottom: disableControl,
    height: disableControl,
    justifyContent: disableControl,
    justifyItems: disableControl,
    justifySelf: disableControl,
    left: disableControl,
    letterSpacing: disableControl,
    lineHeight: disableControl,
    margin: disableControl,
    marginBottom: disableControl,
    marginLeft: disableControl,
    marginRight: disableControl,
    marginTop: disableControl,
    maxHeight: disableControl,
    maxWidth: disableControl,
    minHeight: disableControl,
    minWidth: disableControl,
    noWrap: disableControl,
    order: disableControl,
    overflow: disableControl,
    padding: disableControl,
    paddingBottom: disableControl,
    paddingLeft: disableControl,
    paddingRight: disableControl,
    paddingTop: disableControl,
    paragraph: disableControl,
    position: disableControl,
    ref: disableControl,
    right: disableControl,
    rowGap: disableControl,
    textAlign: disableControl,
    textOverflow: disableControl,
    top: disableControl,
    variantMapping: disableControl,
    visibility: disableControl,
    whiteSpace: disableControl,
    width: disableControl,
  },
  component: JsonComponent,
  title: "Components/Json",
} as Meta

const Template: Story<JsonProps> = (args) => <JsonComponent {...args} />

export const Json = Template.bind({})
Json.args = {
  json: { boolean: true, null: null, number: 1, string: "text" },
  label: "Label",
}
