import { Json as JsonComponent, JsonProps } from "./Json"
import { Meta, Story } from "@storybook/react"

const hideControl = {
  table: {
    disable: true,
  },
}

// noinspection JSUnusedGlobalSymbols
export default {
  argTypes: {
    align: hideControl,
    alignContent: hideControl,
    alignItems: hideControl,
    alignSelf: hideControl,
    borderBottom: hideControl,
    borderColor: hideControl,
    borderLeft: hideControl,
    borderRadius: hideControl,
    borderRight: hideControl,
    borderTop: hideControl,
    bottom: hideControl,
    boxSizing: hideControl,
    classes: hideControl,
    color: hideControl,
    columnGap: hideControl,
    display: hideControl,
    flex: hideControl,
    flexBasis: hideControl,
    flexDirection: hideControl,
    flexGrow: hideControl,
    flexShrink: hideControl,
    flexWrap: hideControl,
    fontFamily: hideControl,
    fontSize: hideControl,
    fontStyle: hideControl,
    gap: hideControl,
    gridArea: hideControl,
    gridAutoColumns: hideControl,
    gridAutoFlow: hideControl,
    gridAutoRows: hideControl,
    gridColumn: hideControl,
    gridRow: hideControl,
    gridTemplateAreas: hideControl,
    gridTemplateColumns: hideControl,
    gridTemplateRows: hideControl,
    gutterBottom: hideControl,
    height: hideControl,
    justifyContent: hideControl,
    justifyItems: hideControl,
    justifySelf: hideControl,
    left: hideControl,
    letterSpacing: hideControl,
    lineHeight: hideControl,
    margin: hideControl,
    marginBottom: hideControl,
    marginLeft: hideControl,
    marginRight: hideControl,
    marginTop: hideControl,
    maxHeight: hideControl,
    maxWidth: hideControl,
    minHeight: hideControl,
    minWidth: hideControl,
    noWrap: hideControl,
    order: hideControl,
    overflow: hideControl,
    padding: hideControl,
    paddingBottom: hideControl,
    paddingLeft: hideControl,
    paddingRight: hideControl,
    paddingTop: hideControl,
    paragraph: hideControl,
    position: hideControl,
    ref: hideControl,
    right: hideControl,
    rowGap: hideControl,
    textAlign: hideControl,
    textOverflow: hideControl,
    top: hideControl,
    variantMapping: hideControl,
    visibility: hideControl,
    whiteSpace: hideControl,
    width: hideControl,
  },
  component: JsonComponent,
  title: "Components/Json",
} as Meta

const Template: Story<JsonProps> = (args) => <JsonComponent {...args} />

export const Json = Template.bind({})
Json.args = {
  json: { boolean: true, null: null, number: 1, string: "text" },
  label: "Label",
}
